# Generated by Django 5.2 on 2025-05-09 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_contraseña_customuser_correo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='company',
            new_name='contrasena',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='contraseña',
        ),
    ]
