# Generated by Django 5.2 on 2025-05-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_company_customuser_contrasena_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='contrasena',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
