services:

  api-song:
    build: .
    container_name: api-song
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_db
      POSTGRES_HOST: 172.31.19.62
      POSTGRES_PORT: 5432
      PORT: 8001
      SPRING_URL: http://api-students:8080
    networks:
      - backend


volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
