version: "3.9"
services:
  api-song:
    build: .
    container_name: api-song
    restart: unless-stopped
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"   # disponible en Docker ≥ 20.10  :contentReference[oaicite:1]{index=1}
networks:
  default:
    name: app-network
