services:
  api-song:
    build: .
    container_name: api-song
    restart: unless-stopped
    ports:
      - "8001:8001"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"   # disponible en Docker ≥ 20.10  :contentReference[oaicite:1]{index=1}
    environment:
      SPRING_URL: http://api-students:8080   # <- hostname del otro servicio
    networks: [backend] 
networks:
  backend:
    external: true               #
