version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    container_name: posts-postgres-dev
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres_data_dev:

networks:
  backend:
    driver: bridge
