services:

  db:
    image: postgres:17
    container_name: api-song-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB} 
    ports:
      - "5432:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    env_file:
      - .env


  api-song:
    build: .
    restart: unless-stopped
    container_name: api-song
    depends_on:
      - db
    ports:
      - "8001:8001"  
    volumes:
      - .:/app

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local