services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_db
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks: [backend]

  api-song:
    build: .
    container_name: api-song
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_db
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      PORT: 8001
      SPRING_URL: http://api-students:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks: [backend]
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  backend:
    external: true
