version: '3.8'

services:
  mysql-extractor:
    build:
      context: .
      dockerfile: mysql_extractor/Dockerfile
    environment:
      - MYSQL_HOST=184.72.225.36
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=test
    volumes:
      - ./data/mysql:/data/output
  postgresql-extractor:
    build:
      context: .
      dockerfile: postgresql_extractor/Dockerfile
    environment:
      - PG_HOST=${PG_HOST}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_DATABASE=${PG_DATABASE}
    volumes:
      - ./data/postgresql:/data/output

  mongodb-extractor:
    build:
      context: .
      dockerfile: mongodb_extractor/Dockerfile
    environment:
      - MONGO_URI=${MONGO_URI}
      - MONGO_DATABASE=${MONGO_DATABASE}
    volumes:
      - ./data/mongodb:/data/output 