version: '3.8'

services:
  mysql-extractor:
    build:
      context: .
      dockerfile: mysql_extractor/Dockerfile
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./data/mysql:/data/output

  postgresql-extractor:
    build:
      context: .
      dockerfile: postgresql_extractor/Dockerfile
    environment:
      - PG_HOST=${PG_HOST}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_DATABASE=${PG_DATABASE}
    volumes:
      - ./data/postgresql:/data/output

  mongodb-extractor:
    build:
      context: .
      dockerfile: mongodb_extractor/Dockerfile
    environment:
      - MONGO_URI=${MONGO_URI}
      - MONGO_DATABASE=${MONGO_DATABASE}
    volumes:
      - ./data/mongodb:/data/output 