services:
  graphql-gateway:
    build: .
    container_name: graphql-gateway
    ports:
      - "4000:4000"
    env_file:
      - .env
    networks:
      - backend

networks:
  backend:
    driver: bridge
