version: '3.8'

services:
  api-students:
    build: .
    container_name: api-students
    restart: unless-stopped
    ports:
      - "8002:8080"
    environment:
      SERVER_PORT: 8080
      SPRING_APPLICATION_NAME: backend-cloud-twit
      SPRING_DATA_MONGODB_URI: mongodb://admin:admin123@172.31.29.139:27017/historialdb?authSource=admin   
      SPRING_DATA_MONGODB_DATABASE: historialdb
      SPRINGDOC_API-DOCS_PATH: /api-docs
      SPRINGDOC_SWAGGER-UI_PATH: /api
    networks:
      - backend

networks:
  backend:
    external: true
