# Generated by Django 5.2 on 2025-05-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_artistico', models.CharField(max_length=100)),
                ('genero_principal', models.CharField(max_length=50)),
            ],
        ),
    ]
