# Generated by Django 5.2 on 2025-05-08 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
        ('users', '0003_customuser_contraseña_customuser_correo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nombre_artistico', models.CharField(max_length=100)),
                ('genero_principal', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
