makemigrations:
	poetry run python manage.py makemigrations
migrate:
	poetry run python manage.py migrate
runserver:
	poetry run python manage.py runserver
startapp:
	poetry run python manage.py startapp


